split ctakes client tests into REST client and COVID symptoms specifi…
comorbidity/ctakes-client-python pull request #7
Opened 2022-09-12 18:11 UTC by comorbidity

…c tests.

Method documentation added.
test_client_covid_symptoms.py
test_client_ctakes_rest_server.py

Negation tests now pass or are skipped (requires HTTP connection to live server) test_negation.py
test_negation_transformer.py

Fixed "custom dict" test
test_typesystem.py

2022-09-12 18:28 UTC, mikix requested changes
Looks mostly fine, but tests still fail for me locally and this should be filed against https://github.com/Machine-Learning-for-Medical-Language/ctakes-client-py not this repo.

2022-09-12 18:28 UTC, mikix commented on tests/test_typesystem.py
> -        self.assertEqual(0, len(reader.list_identified_annotation()), 'no custom dict expected')
There is still value in checking the identified annotations I think - there are legitimately seven annotations in the test file. What about changing this to:

```
expected = {'symptoms', 'headache', 'nausea', 'vomiting', 'cough', 'Diarrhea', 'chest pain'}
annotations = {m.text for m in reader.list_identified_annotation()}
self.assertEqual(expected, annotations)
```

2022-09-12 18:28 UTC, mikix commented on tests/test_client_ctakes_rest_server.py
> +        self.assertDictEqual(expected, actual1, 'JSON did not match round trip serialization')
When I run this test locally, I get a failure because the `conceptAttributes` inside `AnatomicalSiteMention` are in different orders in the json. Is this a situation where we need to make the compare check not worry about order like that, or do we need to update our json file to match what the code is giving out?

2022-09-13 19:05 UTC, comorbidity commented on tests/test_client_ctakes_rest_server.py
> +        self.assertDictEqual(expected, actual1, 'JSON did not match round trip serialization')
Good catch! I haven't seen that, maybe you can show me the issue

2022-09-13 19:08 UTC, comorbidity commented on tests/test_typesystem.py
> -        self.assertEqual(0, len(reader.list_identified_annotation()), 'no custom dict expected')
list_identified_annotation has an issue because the ctakes server is wrongly swapping CUI for CODE. 
I might pull this method entirely, as its use is not documented and misleading.

2022-09-14 13:29 UTC, mikix commented
Merged as part of https://github.com/Machine-Learning-for-Medical-Language/ctakes-client-py/pull/5

2022-09-14 13:29 UTC, closed without merging